name: issue
on: 
  issues:
    types:
      - opened
      - closed
jobs:
  issue-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue details
        run: echo "${{ toJSON(github) }}"