name: push
on: [push]
jobs:
  push-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Copy files
        uses: actions/checkout@v3
      - name: Lint script
        run: echo "lint"
      - name: Test script
        run: echo "test"
      - name: Build script
        run: echo "build"